
# This is a basic workflow to help you get started with Actions

name: WizCLIv1 Windows image scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  wiz-cli-scan:
    name: "WizCLI Scan"
    # The type of runner that the job will run on
    runs-on: windows-latest

    env:
      #SCAN_PATH: "." # Set the relative path in the repo to scan
      # POLICY: "Default IaC policy" # Set the desired Wiz CLI policy to use
      IMAGE: "071499847599.dkr.ecr.us-east-2.amazonaws.com/dotnet-framework-sdk:latest"

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Check out repo
      #  uses: actions/checkout@v4

      - name: Download Wiz CLI
        #run: curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
        run: curl -Lo wizcli.exe https://downloads.wiz.io/v1/wizcli/latest/wizcli-windows-amd64.exe

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -la
          echo ""
          echo "GITHUB_ACTIONS = " + "$GITHUB_ACTIONS"
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_ACTOR"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_SHA"
          echo "$GITHUB_JOB"
          echo "$GITHUB_SERVER_URL"
          echo ""

#      - name: Run wiz CLI IaC scan
#        run: ./wizcli scan dir $SCAN_PATH --client-id "" --log debug.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image
        run: docker pull $IMAGE
        
      - name: Run wiz CLI Image scan
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID_V1 }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET_V1 }}
        run: ./wizcli scan container-image $IMAGE --driver mountWithLayers --log debug.txt
        continue-on-error: true

      - name: Upload Log file
        uses: actions/upload-artifact@v4
        with:
          name: debug_log
          path: debug.txt

      - name: grep log
        run: grep EXCEPTION debug.txt || echo "No exceptions found"
